default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # if using docker, uncomment the below two lines
  host: db
  username: postgres

development:
  <<: *default
  database: db/simulation_development

test:
  <<: *default
  database: db/simulation_test
